# Generated by Django 4.0.2 on 2022-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycard',
            name='comment_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
