# Generated by Django 4.0.2 on 2022-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_card', '0002_replycard_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycard',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
