# Generated by Django 4.0.2 on 2022-05-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_card', '0003_replycard_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replycard',
            name='url',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
