# Generated by Django 4.0.2 on 2022-05-10 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reply_card', '0004_alter_replycard_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_num', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
