# Generated by Django 4.0.2 on 2022-05-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_card', '0005_messagenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagenum',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
