# Generated by Django 4.0.2 on 2022-05-11 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reply_card', '0006_alter_messagenum_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycard',
            name='comment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
