# Generated by Django 4.0.2 on 2022-05-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply_card', '0007_replycard_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replycard',
            name='url',
        ),
    ]
