# Generated by Django 4.0.2 on 2022-03-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedNum',
            new_name='ReadNum',
        ),
    ]
