# Generated by Django 4.0.2 on 2022-03-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_read_num_readnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blogtype'),
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
