# Generated by Django 4.0.2 on 2022-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_comment_root_alter_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
