# Generated by Django 4.0.2 on 2022-05-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_replycard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyCard',
        ),
    ]
